/*
 * Created on 10 Jul 2016 ( Time 20:21:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.service;

import java.util.List;

import com.freeware.foodrestaurantsapp.model.Customer;



/**
 * Business Service Interface for entity Customer.
 */
public interface CustomerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param customerId
	 * @return entity
	 */
	Customer findById( Integer customerId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Customer> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Customer save(Customer entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Customer update(Customer entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Customer create(Customer entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param customerId
	 */
	void delete( Integer customerId );


}
