/*
 * Created on 10 Jul 2016 ( Time 20:21:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.service;

import java.util.List;

import com.freeware.foodrestaurantsapp.model.Fooditem;


/**
 * Business Service Interface for entity Fooditem.
 */
public interface FooditemService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param foodId
	 * @return entity
	 */
	Fooditem findById( Integer foodId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Fooditem> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Fooditem save(Fooditem entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Fooditem update(Fooditem entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Fooditem create(Fooditem entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param foodId
	 */
	void delete( Integer foodId );


}
