/*
 * Created on 10 Jul 2016 ( Time 20:21:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.service;

import java.util.List;

import com.freeware.foodrestaurantsapp.model.Orders;


/**
 * Business Service Interface for entity Orders.
 */
public interface OrdersService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param ordersId
	 * @return entity
	 */
	Orders findById( Integer ordersId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Orders> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Orders save(Orders entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Orders update(Orders entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Orders create(Orders entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param ordersId
	 */
	void delete( Integer ordersId );


}
