/*
 * Created on 10 Jul 2016 ( Time 20:21:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.service;

import java.util.List;

import com.freeware.foodrestaurantsapp.model.Restaurant;


/**
 * Business Service Interface for entity Restaurant.
 */
public interface RestaurantService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param restaurantId
	 * @return entity
	 */
	Restaurant findById( Integer restaurantId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Restaurant> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Restaurant save(Restaurant entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Restaurant update(Restaurant entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Restaurant create(Restaurant entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param restaurantId
	 */
	void delete( Integer restaurantId );


}
