/*
 * Created on 10 Jul 2016 ( Time 19:19:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.freeware.foodrestaurantsapp.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "fooditem"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="fooditem", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="FooditemEntity.countAll", query="SELECT COUNT(x) FROM FooditemEntity x" )
} )
public class FooditemEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="food_id", nullable=false)
    private Integer    foodId       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="food_name", length=2147483647)
    private String     foodName     ;

    @Column(name="restaurant_id")
    private Integer    restaurantId ;

    @Column(name="food_description", length=2147483647)
    private String     foodDescription ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FooditemEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFoodId( Integer foodId ) {
        this.foodId = foodId ;
    }
    public Integer getFoodId() {
        return this.foodId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : food_name ( text ) 
    public void setFoodName( String foodName ) {
        this.foodName = foodName;
    }
    public String getFoodName() {
        return this.foodName;
    }

    //--- DATABASE MAPPING : restaurant_id ( int4 ) 
    public void setRestaurantId( Integer restaurantId ) {
        this.restaurantId = restaurantId;
    }
    public Integer getRestaurantId() {
        return this.restaurantId;
    }

    //--- DATABASE MAPPING : food_description ( varchar ) 
    public void setFoodDescription( String foodDescription ) {
        this.foodDescription = foodDescription;
    }
    public String getFoodDescription() {
        return this.foodDescription;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(foodId);
        sb.append("]:"); 
        sb.append(foodName);
        sb.append("|");
        sb.append(restaurantId);
        sb.append("|");
        sb.append(foodDescription);
        return sb.toString(); 
    } 

}
