/*
 * Created on 10 Jul 2016 ( Time 19:19:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.freeware.foodrestaurantsapp.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "orderquatity"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="orderquatity", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="OrderquatityEntity.countAll", query="SELECT COUNT(x) FROM OrderquatityEntity x" )
} )
public class OrderquatityEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="orderquatity", nullable=false)
    private Integer    orderquatity ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="orders_id")
    private Integer    ordersId     ;

    @Column(name="quatity_id")
    private Integer    quatityId    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OrderquatityEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOrderquatity( Integer orderquatity ) {
        this.orderquatity = orderquatity ;
    }
    public Integer getOrderquatity() {
        return this.orderquatity;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : orders_id ( int4 ) 
    public void setOrdersId( Integer ordersId ) {
        this.ordersId = ordersId;
    }
    public Integer getOrdersId() {
        return this.ordersId;
    }

    //--- DATABASE MAPPING : quatity_id ( int4 ) 
    public void setQuatityId( Integer quatityId ) {
        this.quatityId = quatityId;
    }
    public Integer getQuatityId() {
        return this.quatityId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(orderquatity);
        sb.append("]:"); 
        sb.append(ordersId);
        sb.append("|");
        sb.append(quatityId);
        return sb.toString(); 
    } 

}
