/*
 * Created on 10 Jul 2016 ( Time 19:19:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.freeware.foodrestaurantsapp.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "restaurant"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="restaurant", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RestaurantEntity.countAll", query="SELECT COUNT(x) FROM RestaurantEntity x" )
} )
public class RestaurantEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="restaurant_id", nullable=false)
    private Integer    restaurantId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="restaurant_name", length=2147483647)
    private String     restaurantName ;

    @Column(name="restaurant_address", length=50)
    private String     restaurantAddress ;

    @Column(name="restaurant_phoneno", length=2147483647)
    private String     restaurantPhoneno ;

    @Column(name="restaurant_cityid")
    private Integer    restaurantCityid ;

    @Column(name="restaurant_emailid", length=2147483647)
    private String     restaurantEmailid ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RestaurantEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRestaurantId( Integer restaurantId ) {
        this.restaurantId = restaurantId ;
    }
    public Integer getRestaurantId() {
        return this.restaurantId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : restaurant_name ( text ) 
    public void setRestaurantName( String restaurantName ) {
        this.restaurantName = restaurantName;
    }
    public String getRestaurantName() {
        return this.restaurantName;
    }

    //--- DATABASE MAPPING : restaurant_address ( bpchar ) 
    public void setRestaurantAddress( String restaurantAddress ) {
        this.restaurantAddress = restaurantAddress;
    }
    public String getRestaurantAddress() {
        return this.restaurantAddress;
    }

    //--- DATABASE MAPPING : restaurant_phoneno ( varchar ) 
    public void setRestaurantPhoneno( String restaurantPhoneno ) {
        this.restaurantPhoneno = restaurantPhoneno;
    }
    public String getRestaurantPhoneno() {
        return this.restaurantPhoneno;
    }

    //--- DATABASE MAPPING : restaurant_cityid ( int4 ) 
    public void setRestaurantCityid( Integer restaurantCityid ) {
        this.restaurantCityid = restaurantCityid;
    }
    public Integer getRestaurantCityid() {
        return this.restaurantCityid;
    }

    //--- DATABASE MAPPING : restaurant_emailid ( varchar ) 
    public void setRestaurantEmailid( String restaurantEmailid ) {
        this.restaurantEmailid = restaurantEmailid;
    }
    public String getRestaurantEmailid() {
        return this.restaurantEmailid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(restaurantId);
        sb.append("]:"); 
        sb.append(restaurantName);
        sb.append("|");
        sb.append(restaurantAddress);
        sb.append("|");
        sb.append(restaurantPhoneno);
        sb.append("|");
        sb.append(restaurantCityid);
        sb.append("|");
        sb.append(restaurantEmailid);
        return sb.toString(); 
    } 

}
