/*
 * Created on 10 Jul 2016 ( Time 20:21:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.beanmapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BeanServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BeanServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'FooditemEntity' to 'Fooditem'
	 * @param fooditemEntity
	 *//*
	public Fooditem mapFooditemEntityToFooditem(FooditemEntity fooditemEntity) {
		if(fooditemEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Fooditem fooditem = map(fooditemEntity, Fooditem.class);

		return fooditem;
	}
	
	*//**
	 * Mapping from 'Fooditem' to 'FooditemEntity'
	 * @param fooditem
	 * @param fooditemEntity
	 *//*
	public void mapFooditemToFooditemEntity(Fooditem fooditem, FooditemEntity fooditemEntity) {
		if(fooditem == null) {
			return;
		}

		//--- Generic mapping 
		map(fooditem, fooditemEntity);

	}
*/	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}