/*
 * Created on 10 Jul 2016 ( Time 20:21:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.beanmapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.freeware.foodrestaurantsapp.entity.CustomerEntity;
import com.freeware.foodrestaurantsapp.model.Customer;


/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CustomerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CustomerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CustomerEntity' to 'Customer'
	 * @param customerEntity
	 */
	public Customer mapCustomerEntityToCustomer(CustomerEntity customerEntity) {
		if(customerEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Customer customer = map(customerEntity, Customer.class);

		return customer;
	}
	
	/**
	 * Mapping from 'Customer' to 'CustomerEntity'
	 * @param customer
	 * @param customerEntity
	 */
	public void mapCustomerToCustomerEntity(Customer customer, CustomerEntity customerEntity) {
		if(customer == null) {
			return;
		}

		//--- Generic mapping 
		map(customer, customerEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}