/*
 * Created on 10 Jul 2016 ( Time 20:21:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.beanmapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.freeware.foodrestaurantsapp.entity.QuatitytypeEntity;
import com.freeware.foodrestaurantsapp.model.Quatitytype;


/**
 * Mapping between entity beans and display beans.
 */
@Component
public class QuatitytypeServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public QuatitytypeServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'QuatitytypeEntity' to 'Quatitytype'
	 * @param quatitytypeEntity
	 */
	public Quatitytype mapQuatitytypeEntityToQuatitytype(QuatitytypeEntity quatitytypeEntity) {
		if(quatitytypeEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Quatitytype quatitytype = map(quatitytypeEntity, Quatitytype.class);

		return quatitytype;
	}
	
	/**
	 * Mapping from 'Quatitytype' to 'QuatitytypeEntity'
	 * @param quatitytype
	 * @param quatitytypeEntity
	 */
	public void mapQuatitytypeToQuatitytypeEntity(Quatitytype quatitytype, QuatitytypeEntity quatitytypeEntity) {
		if(quatitytype == null) {
			return;
		}

		//--- Generic mapping 
		map(quatitytype, quatitytypeEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}