/*
 * Created on 10 Jul 2016 ( Time 20:21:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.beanmapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.freeware.foodrestaurantsapp.entity.RestaurantEntity;
import com.freeware.foodrestaurantsapp.model.Restaurant;


/**
 * Mapping between entity beans and display beans.
 */
@Component
public class RestaurantServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public RestaurantServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'RestaurantEntity' to 'Restaurant'
	 * @param restaurantEntity
	 */
	public Restaurant mapRestaurantEntityToRestaurant(RestaurantEntity restaurantEntity) {
		if(restaurantEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Restaurant restaurant = map(restaurantEntity, Restaurant.class);

		return restaurant;
	}
	
	/**
	 * Mapping from 'Restaurant' to 'RestaurantEntity'
	 * @param restaurant
	 * @param restaurantEntity
	 */
	public void mapRestaurantToRestaurantEntity(Restaurant restaurant, RestaurantEntity restaurantEntity) {
		if(restaurant == null) {
			return;
		}

		//--- Generic mapping 
		map(restaurant, restaurantEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}