/*
 * Created on 10 Jul 2016 ( Time 19:32:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.model;

import java.io.Serializable;


/**
 * Java bean for 'Fooditem' entity
 * 
 * @author Telosys Tools
 *
 */
public class Fooditem implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : food_id serial 
    private Integer foodId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : food_name text 
    private String foodName;

    // DB : restaurant_id int4 
    private Integer restaurantId;

    // DB : food_description varchar 
    private String foodDescription;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setFoodId( Integer foodId ) {
        this.foodId = foodId ;
    }

    public Integer getFoodId() {
        return this.foodId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFoodName( String foodName ) {
        this.foodName = foodName;
    }
    public String getFoodName() {
        return this.foodName;
    }

    public void setRestaurantId( Integer restaurantId ) {
        this.restaurantId = restaurantId;
    }
    public Integer getRestaurantId() {
        return this.restaurantId;
    }

    public void setFoodDescription( String foodDescription ) {
        this.foodDescription = foodDescription;
    }
    public String getFoodDescription() {
        return this.foodDescription;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(foodId);
        sb.append("|");
        sb.append(foodName);
        sb.append("|");
        sb.append(restaurantId);
        sb.append("|");
        sb.append(foodDescription);
        return sb.toString(); 
    } 


}
