/*
 * Created on 10 Jul 2016 ( Time 19:32:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.model;

import java.io.Serializable;


/**
 * Java bean for 'Orders' entity
 * 
 * @author Telosys Tools
 *
 */
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : orders_id serial 
    private Integer ordersId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : customer_id int4 
    private Integer customerId;

    // DB : delivery_address varchar 
    private String deliveryAddress;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOrdersId( Integer ordersId ) {
        this.ordersId = ordersId ;
    }

    public Integer getOrdersId() {
        return this.ordersId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCustomerId( Integer customerId ) {
        this.customerId = customerId;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setDeliveryAddress( String deliveryAddress ) {
        this.deliveryAddress = deliveryAddress;
    }
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(ordersId);
        sb.append("|");
        sb.append(customerId);
        sb.append("|");
        sb.append(deliveryAddress);
        return sb.toString(); 
    } 


}
