/*
 * Created on 10 Jul 2016 ( Time 19:32:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.model;

import java.io.Serializable;


/**
 * Java bean for 'Orderquatity' entity
 * 
 * @author Telosys Tools
 *
 */
public class Orderquatity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : orderquatity serial 
    private Integer orderquatity;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : orders_id int4 
    private Integer ordersId;

    // DB : quatity_id int4 
    private Integer quatityId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOrderquatity( Integer orderquatity ) {
        this.orderquatity = orderquatity ;
    }

    public Integer getOrderquatity() {
        return this.orderquatity;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setOrdersId( Integer ordersId ) {
        this.ordersId = ordersId;
    }
    public Integer getOrdersId() {
        return this.ordersId;
    }

    public void setQuatityId( Integer quatityId ) {
        this.quatityId = quatityId;
    }
    public Integer getQuatityId() {
        return this.quatityId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(orderquatity);
        sb.append("|");
        sb.append(ordersId);
        sb.append("|");
        sb.append(quatityId);
        return sb.toString(); 
    } 


}
