/*
 * Created on 10 Jul 2016 ( Time 19:32:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.model;

import java.io.Serializable;


/**
 * Java bean for 'Quatitytype' entity
 * 
 * @author Telosys Tools
 *
 */
public class Quatitytype implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : quatity_id serial 
    private Integer quatityId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : food_id int4 
    private Integer foodId;

    // DB : quatity_type varchar 
    private String quatityType;

    // DB : amount varchar 
    private String amount;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setQuatityId( Integer quatityId ) {
        this.quatityId = quatityId ;
    }

    public Integer getQuatityId() {
        return this.quatityId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFoodId( Integer foodId ) {
        this.foodId = foodId;
    }
    public Integer getFoodId() {
        return this.foodId;
    }

    public void setQuatityType( String quatityType ) {
        this.quatityType = quatityType;
    }
    public String getQuatityType() {
        return this.quatityType;
    }

    public void setAmount( String amount ) {
        this.amount = amount;
    }
    public String getAmount() {
        return this.amount;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(quatityId);
        sb.append("|");
        sb.append(foodId);
        sb.append("|");
        sb.append(quatityType);
        sb.append("|");
        sb.append(amount);
        return sb.toString(); 
    } 


}
