/*
 * Created on 10 Jul 2016 ( Time 19:32:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.freeware.foodrestaurantsapp.model;

import java.io.Serializable;


/**
 * Java bean for 'Restaurant' entity
 * 
 * @author Telosys Tools
 *
 */
public class Restaurant implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : restaurant_id serial 
    private Integer restaurantId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : restaurant_name text 
    private String restaurantName;

    // DB : restaurant_address bpchar 
    private String restaurantAddress;

    // DB : restaurant_phoneno varchar 
    private String restaurantPhoneno;

    // DB : restaurant_cityid int4 
    private Integer restaurantCityid;

    // DB : restaurant_emailid varchar 
    private String restaurantEmailid;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRestaurantId( Integer restaurantId ) {
        this.restaurantId = restaurantId ;
    }

    public Integer getRestaurantId() {
        return this.restaurantId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRestaurantName( String restaurantName ) {
        this.restaurantName = restaurantName;
    }
    public String getRestaurantName() {
        return this.restaurantName;
    }

    public void setRestaurantAddress( String restaurantAddress ) {
        this.restaurantAddress = restaurantAddress;
    }
    public String getRestaurantAddress() {
        return this.restaurantAddress;
    }

    public void setRestaurantPhoneno( String restaurantPhoneno ) {
        this.restaurantPhoneno = restaurantPhoneno;
    }
    public String getRestaurantPhoneno() {
        return this.restaurantPhoneno;
    }

    public void setRestaurantCityid( Integer restaurantCityid ) {
        this.restaurantCityid = restaurantCityid;
    }
    public Integer getRestaurantCityid() {
        return this.restaurantCityid;
    }

    public void setRestaurantEmailid( String restaurantEmailid ) {
        this.restaurantEmailid = restaurantEmailid;
    }
    public String getRestaurantEmailid() {
        return this.restaurantEmailid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(restaurantId);
        sb.append("|");
        sb.append(restaurantName);
        sb.append("|");
        sb.append(restaurantAddress);
        sb.append("|");
        sb.append(restaurantPhoneno);
        sb.append("|");
        sb.append(restaurantCityid);
        sb.append("|");
        sb.append(restaurantEmailid);
        return sb.toString(); 
    } 


}
